{% set name = "attrdict" %}
{% set version = "2.0.1" %}
{% set sha256 = "35c90698b55c683946091177177a9e9c0713a0860f0e049febd72649ccd77b70" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools

  run:
    - python >={{ python_min }},<3.10
    - six

test:
  requires:
    - python {{ python_min }}
  imports:
    - attrdict

about:
  home: https://github.com/bcj/AttrDict/
  license: MIT
  license_file: LICENSE.txt
  summary: A dict with attribute-style access

extra:
  recipe-maintainers:
    - vamega
